name: Auto Comment
on: [issues, pull_request]
permissions:
  pull-requests: write
  issues: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
          pullRequestOpened: |
            👋 @{{ author }}
            Thanks for you contributions! You can assign someone to review your code.
            For reviewers, check out the preview deployment here:
            https://alumni.gunnhigh.school/pr/{{ id }}
